baseurl                 = "http://studentactivism.xyz/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Student Activists!"
theme                   = "sam"
googleAnalytics       = "UA-115774356-1"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
    pygmentsCodefences  = true
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Call me Sam, a theme for Hugo."
    introp              = "If you are here I want to thank you for taking the next step in making a change. We have only just begun"

# Metadata
    description         = "A new Hugo site."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/getinvolved"
    text = "Get Involved"

[[params.mainMenu]]
    link = "/about"
    text = "About"

[[params.mainMenu]]
    link = "/posts"
    text = "Updates"

[[params.mainMenu]]
    link = "/who"
    text = "Who are we?"
